---
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      uv:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directory: /.tf
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      terraform:
        patterns:
          - "*"
